@startuml
Class App {}
class CLI {}
abstract class Product {
#id: int
#name:str
#price: double
}

class ProductHandler {
-products:arrayList<Product>
}

class Ticket{
-products:arrayList<Product>
}

enum status {
EMPTY
ACTIVE
CLOSED
}

Ticket --> status
class TicketHandler {
-ticket : Ticket
}

Product --o ProductHandler
Product --o Ticket
TicketHandler --o Ticket



class ProductBasic{

-id: int
-name:str
-category:Category
-price:double
}

enum Category {
MERCH
ELECTRONICA
PAPELERIA
ROPA
LIBRO
}
ProductBasic -->Category
ProductBasic --|> Product

class ProductPers{

-id:int
-name:str
-category:Category
-price:double
-texts:ArrayList<Str>
}
ProductPers --|> ProductBasic

class CampusMeals{
-maxParticipantes:100
-MINTIME:72
}
CampusMeals --|> Product

class Meeting{
-maxParticipantes:100
-MINTIME:12
}
Meeting --|> Product

class UserHandler{
-Users:ArrayList<User>
}

abstract class User {
}
User --o UserHandler
class Client {
-id
-name
-dni
-mail
-cajero:Cajero
}
Client --|> User


class Cashier{
-code:str
-name
-mail
}
Cashier --|> User

Cashier o-- Ticket
Client o-- Ticket


abstract class Command{
#name:Str
+{abstract}apply(args:String[])
}

class CommandProd{
-commands : arrayList<commands>
+ apply(args : String[])
}

class CommandAddProd{
 + apply(args : String[])
}
CommandAddProd --|> Command
CommandAddProd --*CommandProd
ProductHandler<-- CommandAddProd

class CommandTicket{
-commands : arrayList<commands>
+ apply(args : String[])
}


class CommandNewTicket{
 + apply(args : String[])
}
CommandNewTicket --|> Command
CommandNewTicket --*CommandTicket
TicketHandler <-- CommandNewTicket


class CommandUser{
-commands : arrayList<commands>
+ apply(args : String[])
}

class CommandAddUser{
 + apply(args : String[])
}
CommandAddUser --|> Command
CommandAddUser --*CommandUser
UserHandler <-- CommandAddUser

App --* Command
App --* CLI
App --> ProductHandler
App --> TicketHandler
App --> UserHandler

App *-- CommandProd
App *-- CommandTicket
App *-- CommandUser
@enduml