@startuml
'Estilo:
skinparam backgroundColor #CFEFFA

'Capa 1:-----------------------------------------------
Class App {
    -ticketHandler: TicketHandler
    -userHandler: UserHandler
    -productHandler: ProductHandler

    +{static}main(String[] args): void
}



'Capa 2:-------------------------------------
'grupos y clases
namespace Commands #FFFEDB {
}
namespace Info  #FFAA99{
}
namespace Persistance #FFFEDB {
}
note top of Info
<size:9>Aquí se guardan archivos que poco tienen que ver con el programa en si</size>
<size:9>No creo que se deba representar en el diagrama pero es más visual</size>
end note
class CLI {
    -commandsProducts: CommandProd
    -commandsTicket: CommandTicket
    -commandsUser: CommandUser

    +CLI(CommandProd commandsProductos, CommandTicket commandsTicket, CommandUser commandsUser)
    +start(): void
    +start(String fichero): void
    +dispatcherCentralCommand(String actCommand): void
    +sliceCommand(String args): String[]
    +{static}mostrarComandos(): void
}
class Commands.CommandProd{

    + CommandProd()
    +checkCommand(String[] comdiv, String actCom)
    +addCommand(Command)
}

class Commands.CommandTicket{

    + CommandTicket()
    + checkCommand(String[] comdiv, String actCom)
    + addCommand(Command)
}
class Commands.CommandUser{

    + CommandUser()
    + checkCommand(String[] comdiv, String actCommand)
    + addCommand(Command)
}
class Utilities{
    +{static}MAX_LIST: int = 200;
    +{static}MAX_IN_TICKET: int = 100;
    +{static}MAX_PEOPLE_EVENT: int = 100;
    +{static}MIN_TIME_MEETING: int = 12;
    +{static}MIN_TIME_MEELS: int = 72;
    +{static}MAX_PERS_PRODUCT: int = 10;

    +{static}numGenerator(int cantidad): int
    +{static}idAleatorio(ProductHandler): int
    +{static}isNumeric(String str: boolean)
    +{static}isBusiness(String id): boolean
    +{static}isDNICorrect(String id): boolean
    +{static}getMinTimeMeetings(): int
    +{static}getMinTimeMeels(): int
    +{static}getMaxPersProduct(): int
}
class Comments{
    +{static}LENGTH_WRONG: String
    +{static}TICKET_NEW_OK: String
    +{static}PRODUCT_NOT_FOUND: String
    ...
}
class Persistance.PersistanceManager{
    -ObjectMapper mapper
    -String PRODUCT_FILE
    -String USER_FILE
    -String TICKET_FILE

    +saveProducts(ProductHandler ph): void
    +loadProducts(): productHandler
    +saveUsers(UserHandler uh): void
    +loadUsers(): UserHandler
    +saveTickets(TicketHandler th): saveTickets
    +loadTickets(): TicketHandler
}

'relaciones necesarias:
App ..> CLI
App ..> CommandProd
App ..> CommandTicket
App ..> CommandUser
App ..> PersistanceManager

'relaciones invisibles de orden
App .[hidden]. Commands
CLI .[hidden]right. Commands
CommandProd .[hidden]right. CommandTicket
CommandTicket .[hidden]right. CommandUser
App .[hidden]. Utilities
Commands .[hidden]right. CLI
App .[hidden]. Comments
Utilities .[hidden]right. Comments
Comments .[hidden]right. Info


'capa 3: ---------------------------
interface Commands.Command{
    isThisCommand(String name): boolean
    execute(String args): void
}
'relaciones necesarias:
CommandProd o-- Command
CommandTicket o-- Command
CommandUser o-- Command
'Capa 4:-------------------------
'grupos y clases
class Commands.CommandsForProd.CommandProdEx{
    +CommandProdEx(String name, ProductHandler productHandler)
    +isThisCommand(String name): boolean
    +execute(String[] args)
}
class Commands.CommandsForTicket.CommandTicketEx{
     +CommandTicketEx(String name, TicketHandler ticketHandler, UserHandler userHandler, ProductHandler productHandler*)
     +isThisCommand(String name): boolean
     +execute(String[] args)
}
class Commands.CommandsForUser.CommandUserEx{
    +CommandUserEx(String name, UserHandler userHandler)
    +isThisCommand(String name)
    +execute(String[] args)
}
'relaciones necesarias:
Command <|.. Commands.CommandsForProd.CommandProdEx
Command <|.. Commands.CommandsForTicket.CommandTicketEx
Command <|.. Commands.CommandsForUser.CommandUserEx
CommandProd *-- Commands.CommandsForProd.CommandProdEx
CommandTicket *-- CommandTicketEx
CommandUser *-- CommandUserEx


'relaciones invisibles de orden
CommandProdEx .[hidden]right. CommandTicketEx
Commands.CommandsForProd .[hidden]right. Commands.CommandsForTicket
CommandTicketEx .[hidden]right. CommandUserEx
Commands.CommandsForTicket .[hidden]right. Commands.CommandsForUser


'Capa 5:----------------------------------
'grupos y clases
class ProductHandler {
    -{static}CAPACITY = MAX_LIST

    +ProductHandler()
    +addProduct(Product): boolean
    +removeProduct(int id): void
    +getProduct(int id): Product
    +getProductList(): List<Producto>
    +getHandlerSize(): int
    +updateProduct(id,field,newFact): void
    +updateProductName(id ,newName):void
    +updateProductCategory(id,newCat):void
    +updateProductPrice(id, newPrice): void
    +listProducts():void
    +capacityLeft(): int
    +getCapacity(): int
}
class TicketHandler {

    +TicketHandler()
    +getTickets(): ArrayList<TicketParam<? extends Vendible>>
    +newTicketClient(int idT): int
    +newTicketClient(): int
    +newTicketBusinessService(int idT): int
    +newTicketBusinessService(): int
    +newTicketBusinessCombined(int idT): int
    +newTicketBusinessCombined(): int
    +auxFindIdForTicket(int TId): int
    +addTicket(int TId, Product newproduct ,int cantidad): void
    +getTicket(int TId): TicketParam<? extends Vendible>
    +removeTicket(int TId): boolean
}
class UserHandler{
    -HashMap<String, Client> clientsRecord
    -HashMap<String, Cashier> cashierRecord

    +UserHandler()
    +getUserAmount(): int
    +getClientsRecord(): HashMap<String, Client>
    +getCashiersRecord(): HashMap<String, Cashier>
    +registerUser(User): void
    +getUserById(String id): User
    +listCashierRecord(): void
    +listClientRecord(): void
    +listTicketsCashier(String idCash): void
}

'relaciones necesarias:
CommandProdEx --> ProductHandler
CommandTicketEx --> TicketHandler
CommandUserEx --> UserHandler

CommandProdEx -[norank,#grey,dotted]-> TicketHandler
CommandProdEx -[norank,#grey,dotted]-> UserHandler
CommandTicketEx -[norank,#grey,dotted]-> ProductHandler
CommandTicketEx -[norank,#grey,dotted]-> UserHandler
CommandUserEx -[norank,#grey,dotted]-> ProductHandler
CommandUserEx -[norank,#grey,dotted]-> TicketHandler

App -[norank,#grey,dotted]-> ProductHandler
App -[norank,#grey,dotted]-> TicketHandler
App -[norank,#grey,dotted]-> UserHandler

'capa 6:---------------------------------
'grupos y clases
namespace Products #FFFEDB {
}
namespace Tickets #FFFEDB {
}
namespace Users #FFFEDB {
}
namespace Validacion #FFFEDB{
}
namespace Strategies #FFFEDB{
}
abstract Products.Product<<Abstract>>  {
    #id: int
    #name:str
    #price: double

    +Product(int id, String name, double price)
    +getPrecio(): double
    +setPrice(double precio): void
    +getName(): String
    +setName(String name): void
    +getId(): int
    +equals(Product): boolean
    +{abstract}isPersonalizable(): boolean
    +{abstract}toString(): String
    +{abstract}getCategory(): Category
    +{abstract}totalPrice(): double
    +{abstract}getDiscount(): double
    +{abstract}amountTicket(int amount): int
    +{abstract}getMinTime(): Duration
    +getStartDate(): LocalDateTime
    +{abstract}copyProduct(): Duration
}
abstract class Products.Vendible{
    -String id

    +Vendible()
    +Vendible(String id)
    +getId(): String
    +setId(String id): void
    +toString(): String
    +amountTicket(int amount)
    +isPersonalizable(): boolean
    +copyProduct(): Product
    +getMinTime(): Duration
}

enum Products.Category {
MERCH
ELECTRONICA
PAPELERIA
ROPA
LIBRO
}
enum Products.ServicesTipes{
TRANSPORTES
ESPECTACULOS
SEGUROS
}
abstract class Tickets.TicketParam<T extends Vendible>{
    -id: int
    #stateTicket: State
    -{static}MAXSIZE = 100
    -ticketDateOpen: String
    -ticketDateClose: String

    +TicketParam()
    +TicketParam(int id, PrintStrategy<T> printStrategy, ValidacionAddTickets<T> validacionAddTickets, ValidacionCloseTicket<T> validacionCloseTickets)
    +TicketParam(PrintStrategy<T> printStrategy, ValidacionTickets<T> validacionTickets)
    +Ticket(int id)
    +getTicketDateOpen(): String
    +getTicketDateClose(): String
    +getId(): int
    +getProducts(): ArrayList<TicketItem>
    +getNumeroProductos(): int
    +ticketIsFull(): boolean
    +getTicketState(): State
    +updateState(State stateTicket): void
    +addProduct(T element, int cantidad): void
    +removeProduct(String id): boolean
    +busquedaProductoPorID(ArrayList<TicketItem<T>>, int id): TicketItem
    +getCantidadProductoCategoria(): Map<Category,Integer>
    +printTicket(): void
    +checkIfTicketCanClose(): boolean
    +closeTicket(): void
    +canAdd(T element): boolean
    +listTicket(): String
    +isClientType(): boolean
    +isBusinessType(): boolean
}
Tickets.TicketParam ..> Strategies.PrintStrategy
Tickets.TicketParam ..> Validacion.ValidacionAddTickets
Tickets.TicketParam ..> Validacion.ValidacionCloseTickets

abstract class Users.User<<abstract>> {
    -String dni
    -String nombre
    -String correo

    +User(String dni, String nombre, String correo)
    +getName(): String
    +getMail(): String
    +getId(): String
    +getThisCash(): Cashier
    +getThisCli(): Client
    +isCash(): boolean
    +addTicket(Ticket): void
    +removeTicket(): void
}
class Users.Client {

    +Client(String dni, String nombre, String correo, Cashier cash)
    +getCashier(): Cashier
    +setTicketToClient(Ticket): void
    +getThisCli(): Client
    +removeTicketFromClient(int idTicket): void
    +getTicket(int idT): Ticket
    +getTickets(): HashMap<Integer, Ticket>
}
class Users.Cashier{

    +Cashier(String id, String nombre, String correo)
    +getTickets(): HashMap<Integer,Ticket>
    +addTicket(int id): void
    +removeTicket(int id): void
    +printTicket(int id): void
    +printAllTickets(): void
    +validarId(int id): String
    +listAllTickets(): void
    +getThisCash(): Cashier
    +isCash(): boolean
    +extractNumericId(String CashierId): int
}
class Validacion.ValidacionAddC{
    +add(Vendible vendible) : boolean
}
class Validacion.ValidacionAddP{
    +add(Vendible vendible) : boolean
}
class Validacion.ValidacionAddS{
    +add(Vendible vendible) : boolean
}
interface Validacion.ValidacionAddTickets{
    add(Vendible vendible)
}

class Validacion.ValidacionCloseC{
    +close(TicketParam<Vendible> ticket)
}
class Validacion.ValidacionCloseP{
    +close(TicketParam<Product> ticket)
}
class Validacion.ValidacionCloseS{
    +close(TicketParam<Service> ticket)
}
interface Validacion.ValidacionCloseTickets{
    +close(TicketParam<T> ticket)
}

class Strategies.BusinessPrintStrategyService{
    +printTicket(TicketParam<Service> ticketParam)
}
class Strategies.BusinessPrintStrategyCombined{
    +printTicket(TicketParam<Vendible> ticketParam)
}
class Strategies.ClientPrintStrategy{
    +printTicket(TicketParam<Product> ticketParam)
}
interface Strategies.PrintStrategy{
    printTicket(TicketParam<T> ticketParam): void
}

'relaciones necesarias
ProductHandler o-- Vendible
UserHandler o-- User
TicketHandler o-- TicketParam
User <|--left Client
User <|--right Cashier
UserHandler o-[norank]- Client
UserHandler o-[norank]- Cashier
TicketHandler ..> ValidacionAddS
TicketHandler ..> ValidacionAddC
TicketHandler ..> ValidacionAddP

TicketHandler ..> ValidacionCloseS
TicketHandler ..> ValidacionCloseC
TicketHandler ..> ValidacionCloseP

Validacion.ValidacionAddTickets <|.. Validacion.ValidacionAddS
Validacion.ValidacionAddTickets <|.. Validacion.ValidacionAddC
Validacion.ValidacionAddTickets <|.. Validacion.ValidacionAddP
Validacion.ValidacionAddP .[hidden]right. Validacion.ValidacionAddC
Validacion.ValidacionAddC .[hidden]right. Validacion.ValidacionAddS

Validacion.ValidacionCloseTickets <|.. Validacion.ValidacionCloseS
Validacion.ValidacionCloseTickets <|.. Validacion.ValidacionCloseC
Validacion.ValidacionCloseTickets <|.. Validacion.ValidacionCloseP
Validacion.ValidacionCloseP .[hidden]right. Validacion.ValidacionCloseC
Validacion.ValidacionCloseC .[hidden]right. Validacion.ValidacionCloseS
PrintStrategy <|.. BusinessPrintStrategyService
PrintStrategy <|.. BusinessPrintStrategyCombined
PrintStrategy <|.. ClientPrintStrategy

TicketHandler ..> BusinessPrintStrategyService
TicketHandler ..> BusinessPrintStrategyCombined
TicketHandler ..> ClientPrintStrategy



'capa 7:----------------------------------
'grupos y clases
class Products.ProductBasic{
    -category: Category

    +Product(Category category, int id, String name, double price)
    +isPersonalizable(): boolean
    +toString(): String
    +toString(int num, double amount): String
    +getCategory(): Category
    +setCategory(Category): void
    +totalPrice(): double
    +getDiscount(): double
    +amountTicket(int amount): int
    +getMinTime(): Duration

}
class Products.Event{
    -maxParticipantes: int
    -MAXPEOPLEALLOWED : int
    -{static}MIN_TIME : int
    -dateOfEnd: LocalDateTime

    +CampusMeals(int id, String name, double price, LocalDateTime dateOfEnd, int maxParticipantes)
    +getDateOfEnd(): LocalDateTime
    +getMaxParticipantes(): int
    +getMinTime(): Duration
    +toString(): String
    +toString(int num, int amount): String
    +TotalPrice(): double
    +getDiscount(): double
    +amountTicket(int amount): int
    +getCategory(): Category
    +isPersonalizable(): boolean
    +getStartDate(): LocalDateTime
}
class Products.Service{
    -contador: int
    -maximumDate: LocalDate
    -ServicesTypes: serviceType

    +validDate(LocalDate fecha):boolean
    +getServiceCategory(): String
    +toString() String
    +amountTicket(int amount): int
    +copyProduct(): Product
    +getMinTime(): Duration
}
class Tickets.TicketClient{
    +TicketClient(int id, PrintStrategy<Product> printStrategy, ValidacionTickets<Product> validacion)
    +TicketClient(PrintStrategy<Product> printStrategy, ValidacionTickets<Product> validacion)
}
class Tickets.TicketBusiness{
    +TicketBusiness(int id, PrintStrategy<Vendible> printStrategy,ValidacionTickets<Vendible> validacion)
    +TicketBusiness(PrintStrategy<Vendible> printStrategy,ValidacionTickets<Vendible> validacion)
}


'relaciones necesarias
Product <|-- Products.ProductBasic
Product <|-- Products.Event
Vendible <|-- Products.Service
TicketParam <|-[#3D61E3]- TicketClient
TicketParam <|-[#05AB74]- Tickets.TicketBusiness

Vendible <|-left- Product
Vendible <.. Validacion.ValidacionAddTickets

TicketClient -[norank,#3D61E3]-o Cashier
TicketClient -[norank,#3D61E3]-o Client
TicketBusiness -[norank,#05AB74]-o Cashier
TicketBusiness -[norank,#05AB74]-o Client

'relaciones invisibles de orden


'capa 8:----------------------------------
'grupos y clases
class TicketItem{
    -amount: int

    +TicketItem(Product product, int amount)
    +getProduct(): Product
    +getAmount(): int
    +addAmount(int n): void
    +subtotal(): double
}
class Products.ProductPers{

    -texts:ArrayList<Str>
    -MAX_TEXTOS: int
    -{static}MAX_PERS = 10

    +ProductPers(Category category,int id, String name, double price, int maxText)
    +addText(String text): boolean
    +getMaxText(): int
    +toString(): String
    +toString(int num, duble amount): String
    +totalPrice(): double
    +isFull(): boolean
    +isPersonalizable(): boolean
}

'relaciones necesarias
TicketClient o-[#3D61E3]- TicketItem
TicketBusiness o-[#05AB74]- TicketItem
Products.ProductBasic <|-- ProductPers
Product <-[norank]- TicketItem

'relaciones invisibles de orden



'capa X:----------------------------------
'grupos y clases
'relaciones necesarias
'relaciones invisibles de orden
@enduml